### ISSUE TITLE
Broken UI left navigation

### ISSUE THREAD

**Issue by alexgheorghiu** [PrivateSky/pskwebcomponents#7]
When adding more text for an entry inside menu.json 

![image](https://user-images.githubusercontent.com/1814282/97853091-50ef5600-1d00-11eb-8996-3edccecb0930.png)

the menu of left seems to look broken (see bellow):

![image](https://user-images.githubusercontent.com/1814282/97853056-42a13a00-1d00-11eb-988a-ae089dbf73de.png)

**Comment by denypatrascu** [comment]
Done.

Modifications were made in [cardinal-w3c-theme (66cdacc)](https://github.com/PrivateSky/cardinal-w3c-theme/commit/66cdacc1459ff13161bf3aff9768786a8c5be82c). 
Now, the width of the sidebar will be adjusted automatically.

In [opendsu](https://opendsu.com) website an update of cardinal was required.

![opendsu-ui](https://user-images.githubusercontent.com/18448426/97879806-11892f80-1d29-11eb-8a9a-b59ef778af16.png)
